workflows:
  dai-workflow:
    name: Android Espresso Tests
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - DAI
      vars:
        PACKAGE_NAME: "com.example.uitestapp"
      java: 17
    scripts:
      - name: Set Android SDK location
        script: |          
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android Test release
        script: |
          ./gradlew assembleAndroidTest
      - name: Build Android release
        script: |
          # Set environment variable so it can be used to increment build number in android/app/build.gradle
          # export NEW_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks=alpha) + 1))             

          export NEW_BUILD_NUMBER=$(($(firebase-app-distribution get-latest-build-number --package-name "$PACKAGE_NAME") + 1))
          ./gradlew assembleRelease
      - name: DigitalAi upload
        script: |      
            APP_URL=$(curl -X POST "https://globaldemo.experitest.com/api/v1/applications/new" \
              -H "Authorization: Bearer $access_key" \
              -F file=@app/build/outputs/apk/release/app-release.apk \
              -F "uniqueName=vstest_1")

            TEST_URL=$(curl -X POST 'https://globaldemo.experitest.com/api/v1/test-run/execute-test-run-async' \
              -H 'Authorization: Bearer $access_key' \
              -F "executionType=Espresso" \
              -F "runningType=fastFeedback" \
              -F app=@app/build/outputs/apk/release/app-release.apk \
              -F testApp=@app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
              -F 'deviceQueries="@os='\''android'\''"' \
              -F "useTestOrchestrator=true") 
    artifacts:
        - app/build/outputs/**/*.apk
